server:
  port: 8082
spring:
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: create
bot:
  name: Fartuck_CK_bot
  token: 6427072962:AAFiFdORl7RCZWdiMzmxWwBiwDwrcwYdJlQ